# Generated by Django 5.2 on 2026-08-13 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Emp_Id', models.IntegerField()),
                ('Phone', models.CharField(max_length=10)),
                ('Address', models.CharField(max_length=100)),
                ('Working', models.BooleanField(default=True)),
                ('Department', models.CharField(max_length=100)),
            ],
        ),
    ]
