# Generated by Django 5.2 on 2026-08-13 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='Email',
            field=models.EmailField(default='unknown@example.com', max_length=100),
            preserve_default=False,
        ),
    ]
