# Generated by Django 5.2 on 2026-08-13 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0002_employee_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='Email',
            field=models.EmailField(max_length=254),
        ),
    ]
