# Generated by Django 5.2 on 2026-08-18 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0004_testimonals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonals',
            name='picture',
            field=models.ImageField(upload_to='media/testimonials/'),
        ),
    ]
